//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for ItemBaseDefaultCarryStatus.
const (
	ItemBaseDefaultCarryStatusPacked ItemBaseDefaultCarryStatus = "packed"
	ItemBaseDefaultCarryStatusWorn   ItemBaseDefaultCarryStatus = "worn"
)

// Valid indicates whether the value is a known member of the ItemBaseDefaultCarryStatus enum.
func (e ItemBaseDefaultCarryStatus) Valid() bool {
	switch e {
	case ItemBaseDefaultCarryStatusPacked:
		return true
	case ItemBaseDefaultCarryStatusWorn:
		return true
	default:
		return false
	}
}

// Defines values for ItemCreateDefaultCarryStatus.
const (
	ItemCreateDefaultCarryStatusPacked ItemCreateDefaultCarryStatus = "packed"
	ItemCreateDefaultCarryStatusWorn   ItemCreateDefaultCarryStatus = "worn"
)

// Valid indicates whether the value is a known member of the ItemCreateDefaultCarryStatus enum.
func (e ItemCreateDefaultCarryStatus) Valid() bool {
	switch e {
	case ItemCreateDefaultCarryStatusPacked:
		return true
	case ItemCreateDefaultCarryStatusWorn:
		return true
	default:
		return false
	}
}

// Defines values for ItemTypeBaseProfile.
const (
	ItemTypeBaseProfileConsumable  ItemTypeBaseProfile = "consumable"
	ItemTypeBaseProfileElectronics ItemTypeBaseProfile = "electronics"
	ItemTypeBaseProfileShelter     ItemTypeBaseProfile = "shelter"
	ItemTypeBaseProfileSleep       ItemTypeBaseProfile = "sleep"
	ItemTypeBaseProfileWearable    ItemTypeBaseProfile = "wearable"
)

// Valid indicates whether the value is a known member of the ItemTypeBaseProfile enum.
func (e ItemTypeBaseProfile) Valid() bool {
	switch e {
	case ItemTypeBaseProfileConsumable:
		return true
	case ItemTypeBaseProfileElectronics:
		return true
	case ItemTypeBaseProfileShelter:
		return true
	case ItemTypeBaseProfileSleep:
		return true
	case ItemTypeBaseProfileWearable:
		return true
	default:
		return false
	}
}

// Defines values for ItemTypeCreateBaseProfile.
const (
	ItemTypeCreateBaseProfileConsumable  ItemTypeCreateBaseProfile = "consumable"
	ItemTypeCreateBaseProfileElectronics ItemTypeCreateBaseProfile = "electronics"
	ItemTypeCreateBaseProfileShelter     ItemTypeCreateBaseProfile = "shelter"
	ItemTypeCreateBaseProfileSleep       ItemTypeCreateBaseProfile = "sleep"
	ItemTypeCreateBaseProfileWearable    ItemTypeCreateBaseProfile = "wearable"
)

// Valid indicates whether the value is a known member of the ItemTypeCreateBaseProfile enum.
func (e ItemTypeCreateBaseProfile) Valid() bool {
	switch e {
	case ItemTypeCreateBaseProfileConsumable:
		return true
	case ItemTypeCreateBaseProfileElectronics:
		return true
	case ItemTypeCreateBaseProfileShelter:
		return true
	case ItemTypeCreateBaseProfileSleep:
		return true
	case ItemTypeCreateBaseProfileWearable:
		return true
	default:
		return false
	}
}

// Defines values for ItemTypeFieldDataType.
const (
	ItemTypeFieldDataTypeBoolean ItemTypeFieldDataType = "boolean"
	ItemTypeFieldDataTypeEnum    ItemTypeFieldDataType = "enum"
	ItemTypeFieldDataTypeInteger ItemTypeFieldDataType = "integer"
	ItemTypeFieldDataTypeNumber  ItemTypeFieldDataType = "number"
	ItemTypeFieldDataTypeString  ItemTypeFieldDataType = "string"
)

// Valid indicates whether the value is a known member of the ItemTypeFieldDataType enum.
func (e ItemTypeFieldDataType) Valid() bool {
	switch e {
	case ItemTypeFieldDataTypeBoolean:
		return true
	case ItemTypeFieldDataTypeEnum:
		return true
	case ItemTypeFieldDataTypeInteger:
		return true
	case ItemTypeFieldDataTypeNumber:
		return true
	case ItemTypeFieldDataTypeString:
		return true
	default:
		return false
	}
}

// Defines values for ItemTypeFieldInputDataType.
const (
	ItemTypeFieldInputDataTypeBoolean ItemTypeFieldInputDataType = "boolean"
	ItemTypeFieldInputDataTypeEnum    ItemTypeFieldInputDataType = "enum"
	ItemTypeFieldInputDataTypeInteger ItemTypeFieldInputDataType = "integer"
	ItemTypeFieldInputDataTypeNumber  ItemTypeFieldInputDataType = "number"
	ItemTypeFieldInputDataTypeString  ItemTypeFieldInputDataType = "string"
)

// Valid indicates whether the value is a known member of the ItemTypeFieldInputDataType enum.
func (e ItemTypeFieldInputDataType) Valid() bool {
	switch e {
	case ItemTypeFieldInputDataTypeBoolean:
		return true
	case ItemTypeFieldInputDataTypeEnum:
		return true
	case ItemTypeFieldInputDataTypeInteger:
		return true
	case ItemTypeFieldInputDataTypeNumber:
		return true
	case ItemTypeFieldInputDataTypeString:
		return true
	default:
		return false
	}
}

// Defines values for ItemTypeUpdateBaseProfile.
const (
	Consumable  ItemTypeUpdateBaseProfile = "consumable"
	Electronics ItemTypeUpdateBaseProfile = "electronics"
	Shelter     ItemTypeUpdateBaseProfile = "shelter"
	Sleep       ItemTypeUpdateBaseProfile = "sleep"
	Wearable    ItemTypeUpdateBaseProfile = "wearable"
)

// Valid indicates whether the value is a known member of the ItemTypeUpdateBaseProfile enum.
func (e ItemTypeUpdateBaseProfile) Valid() bool {
	switch e {
	case Consumable:
		return true
	case Electronics:
		return true
	case Shelter:
		return true
	case Sleep:
		return true
	case Wearable:
		return true
	default:
		return false
	}
}

// Defines values for ItemUpdateDefaultCarryStatus.
const (
	ItemUpdateDefaultCarryStatusPacked ItemUpdateDefaultCarryStatus = "packed"
	ItemUpdateDefaultCarryStatusWorn   ItemUpdateDefaultCarryStatus = "worn"
)

// Valid indicates whether the value is a known member of the ItemUpdateDefaultCarryStatus enum.
func (e ItemUpdateDefaultCarryStatus) Valid() bool {
	switch e {
	case ItemUpdateDefaultCarryStatusPacked:
		return true
	case ItemUpdateDefaultCarryStatusWorn:
		return true
	default:
		return false
	}
}

// Defines values for PackTripType.
const (
	PackTripTypeDayHike   PackTripType = "day_hike"
	PackTripTypeMultiDay  PackTripType = "multi_day"
	PackTripTypeOvernight PackTripType = "overnight"
	PackTripTypeThruHike  PackTripType = "thru_hike"
)

// Valid indicates whether the value is a known member of the PackTripType enum.
func (e PackTripType) Valid() bool {
	switch e {
	case PackTripTypeDayHike:
		return true
	case PackTripTypeMultiDay:
		return true
	case PackTripTypeOvernight:
		return true
	case PackTripTypeThruHike:
		return true
	default:
		return false
	}
}

// Defines values for PackCreateTripType.
const (
	PackCreateTripTypeDayHike   PackCreateTripType = "day_hike"
	PackCreateTripTypeMultiDay  PackCreateTripType = "multi_day"
	PackCreateTripTypeOvernight PackCreateTripType = "overnight"
	PackCreateTripTypeThruHike  PackCreateTripType = "thru_hike"
)

// Valid indicates whether the value is a known member of the PackCreateTripType enum.
func (e PackCreateTripType) Valid() bool {
	switch e {
	case PackCreateTripTypeDayHike:
		return true
	case PackCreateTripTypeMultiDay:
		return true
	case PackCreateTripTypeOvernight:
		return true
	case PackCreateTripTypeThruHike:
		return true
	default:
		return false
	}
}

// Defines values for PackItemCreateCarryStatus.
const (
	PackItemCreateCarryStatusPacked PackItemCreateCarryStatus = "packed"
	PackItemCreateCarryStatusWorn   PackItemCreateCarryStatus = "worn"
)

// Valid indicates whether the value is a known member of the PackItemCreateCarryStatus enum.
func (e PackItemCreateCarryStatus) Valid() bool {
	switch e {
	case PackItemCreateCarryStatusPacked:
		return true
	case PackItemCreateCarryStatusWorn:
		return true
	default:
		return false
	}
}

// Defines values for PackItemUpdateCarryStatus.
const (
	PackItemUpdateCarryStatusPacked PackItemUpdateCarryStatus = "packed"
	PackItemUpdateCarryStatusWorn   PackItemUpdateCarryStatus = "worn"
)

// Valid indicates whether the value is a known member of the PackItemUpdateCarryStatus enum.
func (e PackItemUpdateCarryStatus) Valid() bool {
	switch e {
	case PackItemUpdateCarryStatusPacked:
		return true
	case PackItemUpdateCarryStatusWorn:
		return true
	default:
		return false
	}
}

// Defines values for PackItemWithDetailsCarryStatus.
const (
	PackItemWithDetailsCarryStatusPacked PackItemWithDetailsCarryStatus = "packed"
	PackItemWithDetailsCarryStatusWorn   PackItemWithDetailsCarryStatus = "worn"
)

// Valid indicates whether the value is a known member of the PackItemWithDetailsCarryStatus enum.
func (e PackItemWithDetailsCarryStatus) Valid() bool {
	switch e {
	case PackItemWithDetailsCarryStatusPacked:
		return true
	case PackItemWithDetailsCarryStatusWorn:
		return true
	default:
		return false
	}
}

// Defines values for PackUpdateTripType.
const (
	DayHike   PackUpdateTripType = "day_hike"
	MultiDay  PackUpdateTripType = "multi_day"
	Overnight PackUpdateTripType = "overnight"
	ThruHike  PackUpdateTripType = "thru_hike"
)

// Valid indicates whether the value is a known member of the PackUpdateTripType enum.
func (e PackUpdateTripType) Valid() bool {
	switch e {
	case DayHike:
		return true
	case MultiDay:
		return true
	case Overnight:
		return true
	case ThruHike:
		return true
	default:
		return false
	}
}

// Defines values for PersonConditioningLevel.
const (
	PersonConditioningLevelAthletic  PersonConditioningLevel = "athletic"
	PersonConditioningLevelAverage   PersonConditioningLevel = "average"
	PersonConditioningLevelMilitary  PersonConditioningLevel = "military"
	PersonConditioningLevelSedentary PersonConditioningLevel = "sedentary"
)

// Valid indicates whether the value is a known member of the PersonConditioningLevel enum.
func (e PersonConditioningLevel) Valid() bool {
	switch e {
	case PersonConditioningLevelAthletic:
		return true
	case PersonConditioningLevelAverage:
		return true
	case PersonConditioningLevelMilitary:
		return true
	case PersonConditioningLevelSedentary:
		return true
	default:
		return false
	}
}

// Defines values for PersonGender.
const (
	PersonGenderFemale PersonGender = "female"
	PersonGenderMale   PersonGender = "male"
	PersonGenderOther  PersonGender = "other"
)

// Valid indicates whether the value is a known member of the PersonGender enum.
func (e PersonGender) Valid() bool {
	switch e {
	case PersonGenderFemale:
		return true
	case PersonGenderMale:
		return true
	case PersonGenderOther:
		return true
	default:
		return false
	}
}

// Defines values for PersonCreateConditioningLevel.
const (
	PersonCreateConditioningLevelAthletic  PersonCreateConditioningLevel = "athletic"
	PersonCreateConditioningLevelAverage   PersonCreateConditioningLevel = "average"
	PersonCreateConditioningLevelMilitary  PersonCreateConditioningLevel = "military"
	PersonCreateConditioningLevelSedentary PersonCreateConditioningLevel = "sedentary"
)

// Valid indicates whether the value is a known member of the PersonCreateConditioningLevel enum.
func (e PersonCreateConditioningLevel) Valid() bool {
	switch e {
	case PersonCreateConditioningLevelAthletic:
		return true
	case PersonCreateConditioningLevelAverage:
		return true
	case PersonCreateConditioningLevelMilitary:
		return true
	case PersonCreateConditioningLevelSedentary:
		return true
	default:
		return false
	}
}

// Defines values for PersonCreateGender.
const (
	PersonCreateGenderFemale PersonCreateGender = "female"
	PersonCreateGenderMale   PersonCreateGender = "male"
	PersonCreateGenderOther  PersonCreateGender = "other"
)

// Valid indicates whether the value is a known member of the PersonCreateGender enum.
func (e PersonCreateGender) Valid() bool {
	switch e {
	case PersonCreateGenderFemale:
		return true
	case PersonCreateGenderMale:
		return true
	case PersonCreateGenderOther:
		return true
	default:
		return false
	}
}

// Defines values for PersonUpdateConditioningLevel.
const (
	Athletic  PersonUpdateConditioningLevel = "athletic"
	Average   PersonUpdateConditioningLevel = "average"
	Military  PersonUpdateConditioningLevel = "military"
	Sedentary PersonUpdateConditioningLevel = "sedentary"
)

// Valid indicates whether the value is a known member of the PersonUpdateConditioningLevel enum.
func (e PersonUpdateConditioningLevel) Valid() bool {
	switch e {
	case Athletic:
		return true
	case Average:
		return true
	case Military:
		return true
	case Sedentary:
		return true
	default:
		return false
	}
}

// Defines values for PersonUpdateGender.
const (
	Female PersonUpdateGender = "female"
	Male   PersonUpdateGender = "male"
	Other  PersonUpdateGender = "other"
)

// Valid indicates whether the value is a known member of the PersonUpdateGender enum.
func (e PersonUpdateGender) Valid() bool {
	switch e {
	case Female:
		return true
	case Male:
		return true
	case Other:
		return true
	default:
		return false
	}
}

// Defines values for SettingsCurrency.
const (
	SettingsCurrencyEur SettingsCurrency = "eur"
	SettingsCurrencyUsd SettingsCurrency = "usd"
)

// Valid indicates whether the value is a known member of the SettingsCurrency enum.
func (e SettingsCurrency) Valid() bool {
	switch e {
	case SettingsCurrencyEur:
		return true
	case SettingsCurrencyUsd:
		return true
	default:
		return false
	}
}

// Defines values for SettingsDistanceUnit.
const (
	SettingsDistanceUnitKm SettingsDistanceUnit = "km"
	SettingsDistanceUnitMi SettingsDistanceUnit = "mi"
)

// Valid indicates whether the value is a known member of the SettingsDistanceUnit enum.
func (e SettingsDistanceUnit) Valid() bool {
	switch e {
	case SettingsDistanceUnitKm:
		return true
	case SettingsDistanceUnitMi:
		return true
	default:
		return false
	}
}

// Defines values for SettingsTemperatureUnit.
const (
	SettingsTemperatureUnitC SettingsTemperatureUnit = "c"
	SettingsTemperatureUnitF SettingsTemperatureUnit = "f"
)

// Valid indicates whether the value is a known member of the SettingsTemperatureUnit enum.
func (e SettingsTemperatureUnit) Valid() bool {
	switch e {
	case SettingsTemperatureUnitC:
		return true
	case SettingsTemperatureUnitF:
		return true
	default:
		return false
	}
}

// Defines values for SettingsVolumeUnit.
const (
	SettingsVolumeUnitFlOz SettingsVolumeUnit = "fl_oz"
	SettingsVolumeUnitMl   SettingsVolumeUnit = "ml"
)

// Valid indicates whether the value is a known member of the SettingsVolumeUnit enum.
func (e SettingsVolumeUnit) Valid() bool {
	switch e {
	case SettingsVolumeUnitFlOz:
		return true
	case SettingsVolumeUnitMl:
		return true
	default:
		return false
	}
}

// Defines values for SettingsWeightUnit.
const (
	SettingsWeightUnitG  SettingsWeightUnit = "g"
	SettingsWeightUnitOz SettingsWeightUnit = "oz"
)

// Valid indicates whether the value is a known member of the SettingsWeightUnit enum.
func (e SettingsWeightUnit) Valid() bool {
	switch e {
	case SettingsWeightUnitG:
		return true
	case SettingsWeightUnitOz:
		return true
	default:
		return false
	}
}

// Defines values for SettingsUpdateCurrency.
const (
	SettingsUpdateCurrencyEur SettingsUpdateCurrency = "eur"
	SettingsUpdateCurrencyUsd SettingsUpdateCurrency = "usd"
)

// Valid indicates whether the value is a known member of the SettingsUpdateCurrency enum.
func (e SettingsUpdateCurrency) Valid() bool {
	switch e {
	case SettingsUpdateCurrencyEur:
		return true
	case SettingsUpdateCurrencyUsd:
		return true
	default:
		return false
	}
}

// Defines values for SettingsUpdateDistanceUnit.
const (
	SettingsUpdateDistanceUnitKm SettingsUpdateDistanceUnit = "km"
	SettingsUpdateDistanceUnitMi SettingsUpdateDistanceUnit = "mi"
)

// Valid indicates whether the value is a known member of the SettingsUpdateDistanceUnit enum.
func (e SettingsUpdateDistanceUnit) Valid() bool {
	switch e {
	case SettingsUpdateDistanceUnitKm:
		return true
	case SettingsUpdateDistanceUnitMi:
		return true
	default:
		return false
	}
}

// Defines values for SettingsUpdateTemperatureUnit.
const (
	SettingsUpdateTemperatureUnitC SettingsUpdateTemperatureUnit = "c"
	SettingsUpdateTemperatureUnitF SettingsUpdateTemperatureUnit = "f"
)

// Valid indicates whether the value is a known member of the SettingsUpdateTemperatureUnit enum.
func (e SettingsUpdateTemperatureUnit) Valid() bool {
	switch e {
	case SettingsUpdateTemperatureUnitC:
		return true
	case SettingsUpdateTemperatureUnitF:
		return true
	default:
		return false
	}
}

// Defines values for SettingsUpdateVolumeUnit.
const (
	SettingsUpdateVolumeUnitFlOz SettingsUpdateVolumeUnit = "fl_oz"
	SettingsUpdateVolumeUnitMl   SettingsUpdateVolumeUnit = "ml"
)

// Valid indicates whether the value is a known member of the SettingsUpdateVolumeUnit enum.
func (e SettingsUpdateVolumeUnit) Valid() bool {
	switch e {
	case SettingsUpdateVolumeUnitFlOz:
		return true
	case SettingsUpdateVolumeUnitMl:
		return true
	default:
		return false
	}
}

// Defines values for SettingsUpdateWeightUnit.
const (
	SettingsUpdateWeightUnitG  SettingsUpdateWeightUnit = "g"
	SettingsUpdateWeightUnitOz SettingsUpdateWeightUnit = "oz"
)

// Valid indicates whether the value is a known member of the SettingsUpdateWeightUnit enum.
func (e SettingsUpdateWeightUnit) Valid() bool {
	switch e {
	case SettingsUpdateWeightUnitG:
		return true
	case SettingsUpdateWeightUnitOz:
		return true
	default:
		return false
	}
}

// Item defines model for Item.
type Item = ItemBase

// ItemBase defines model for ItemBase.
type ItemBase struct {
	// Attributes Dynamic per-item values keyed by item type field definitions
	Attributes         *map[string]interface{}     `json:"attributes,omitempty"`
	CreatedAt          time.Time                   `json:"created_at"`
	DefaultCarryStatus *ItemBaseDefaultCarryStatus `json:"default_carry_status,omitempty"`
	DefaultQuantity    *int                        `json:"default_quantity,omitempty"`
	Description        *string                     `json:"description,omitempty"`
	Id                 openapi_types.UUID          `json:"id"`
	ImageBlob          *[]byte                     `json:"image_blob,omitempty"`
	ImageHeightPx      *int                        `json:"image_height_px,omitempty"`
	ImageMimeType      *string                     `json:"image_mime_type,omitempty"`
	ImageSizeBytes     *int                        `json:"image_size_bytes,omitempty"`
	ImageWidthPx       *int                        `json:"image_width_px,omitempty"`
	IsActive           bool                        `json:"is_active"`
	IsDefault          *bool                       `json:"is_default,omitempty"`
	ManufacturerId     openapi_types.UUID          `json:"manufacturer_id"`
	Name               string                      `json:"name"`
	SourceUrl          *string                     `json:"source_url,omitempty"`
	Type               string                      `json:"type"`
	UpdatedAt          time.Time                   `json:"updated_at"`
	Value              *float32                    `json:"value,omitempty"`
	VolumeMl           *float32                    `json:"volume_ml,omitempty"`
	WeightGrams        *float32                    `json:"weight_grams,omitempty"`
}

// ItemBaseDefaultCarryStatus defines model for ItemBase.DefaultCarryStatus.
type ItemBaseDefaultCarryStatus string

// ItemCreate defines model for ItemCreate.
type ItemCreate struct {
	// Attributes Dynamic per-item values keyed by item type field definitions
	Attributes         *map[string]interface{}       `json:"attributes,omitempty"`
	DefaultCarryStatus *ItemCreateDefaultCarryStatus `json:"default_carry_status,omitempty"`
	DefaultQuantity    *int                          `json:"default_quantity,omitempty"`
	Description        *string                       `json:"description,omitempty"`
	ImageBlob          *[]byte                       `json:"image_blob,omitempty"`
	ImageHeightPx      *int                          `json:"image_height_px,omitempty"`
	ImageMimeType      *string                       `json:"image_mime_type,omitempty"`
	ImageSizeBytes     *int                          `json:"image_size_bytes,omitempty"`
	ImageWidthPx       *int                          `json:"image_width_px,omitempty"`
	IsActive           bool                          `json:"is_active"`
	IsDefault          *bool                         `json:"is_default,omitempty"`
	ManufacturerId     openapi_types.UUID            `json:"manufacturer_id"`
	Name               string                        `json:"name"`
	SourceUrl          *string                       `json:"source_url,omitempty"`
	Type               string                        `json:"type"`
	Value              *float32                      `json:"value,omitempty"`
	VolumeMl           *float32                      `json:"volume_ml,omitempty"`
	WeightGrams        *float32                      `json:"weight_grams,omitempty"`
}

// ItemCreateDefaultCarryStatus defines model for ItemCreate.DefaultCarryStatus.
type ItemCreateDefaultCarryStatus string

// ItemSet defines model for ItemSet.
type ItemSet struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`

	// SetCategory Item type id used to categorize this set
	SetCategory string    `json:"set_category"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// ItemSetCreate defines model for ItemSetCreate.
type ItemSetCreate struct {
	Name string `json:"name"`

	// SetCategory Item type id used to categorize this set
	SetCategory string `json:"set_category"`
}

// ItemSetUpdate defines model for ItemSetUpdate.
type ItemSetUpdate struct {
	Name        *string `json:"name,omitempty"`
	SetCategory string  `json:"set_category"`
}

// ItemType defines model for ItemType.
type ItemType struct {
	BaseProfile *ItemTypeBaseProfile `json:"base_profile,omitempty"`
	CreatedAt   time.Time            `json:"created_at"`
	Description *string              `json:"description,omitempty"`

	// Id Machine key for the item type, e.g. consumable or my_power_kit
	Id        string    `json:"id"`
	IsSystem  bool      `json:"is_system"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ItemTypeBaseProfile defines model for ItemType.BaseProfile.
type ItemTypeBaseProfile string

// ItemTypeCreate defines model for ItemTypeCreate.
type ItemTypeCreate struct {
	BaseProfile *ItemTypeCreateBaseProfile `json:"base_profile,omitempty"`
	Description *string                    `json:"description,omitempty"`
	Id          string                     `json:"id"`
	Name        string                     `json:"name"`
}

// ItemTypeCreateBaseProfile defines model for ItemTypeCreate.BaseProfile.
type ItemTypeCreateBaseProfile string

// ItemTypeField defines model for ItemTypeField.
type ItemTypeField struct {
	CreatedAt   time.Time             `json:"created_at"`
	DataType    ItemTypeFieldDataType `json:"data_type"`
	EnumOptions *[]string             `json:"enum_options,omitempty"`
	FieldKey    string                `json:"field_key"`
	FieldLabel  string                `json:"field_label"`
	Id          openapi_types.UUID    `json:"id"`
	IsRequired  bool                  `json:"is_required"`
	ItemTypeId  string                `json:"item_type_id"`
	MaxValue    *float32              `json:"max_value,omitempty"`
	MinValue    *float32              `json:"min_value,omitempty"`
	SortOrder   int                   `json:"sort_order"`
	Unit        *string               `json:"unit,omitempty"`
	UpdatedAt   time.Time             `json:"updated_at"`
}

// ItemTypeFieldDataType defines model for ItemTypeField.DataType.
type ItemTypeFieldDataType string

// ItemTypeFieldInput defines model for ItemTypeFieldInput.
type ItemTypeFieldInput struct {
	DataType    ItemTypeFieldInputDataType `json:"data_type"`
	EnumOptions *[]string                  `json:"enum_options,omitempty"`
	FieldKey    string                     `json:"field_key"`
	FieldLabel  string                     `json:"field_label"`
	IsRequired  *bool                      `json:"is_required,omitempty"`
	MaxValue    *float32                   `json:"max_value,omitempty"`
	MinValue    *float32                   `json:"min_value,omitempty"`
	SortOrder   *int                       `json:"sort_order,omitempty"`
	Unit        *string                    `json:"unit,omitempty"`
}

// ItemTypeFieldInputDataType defines model for ItemTypeFieldInput.DataType.
type ItemTypeFieldInputDataType string

// ItemTypeFieldsReplace defines model for ItemTypeFieldsReplace.
type ItemTypeFieldsReplace struct {
	Fields []ItemTypeFieldInput `json:"fields"`
}

// ItemTypeUpdate defines model for ItemTypeUpdate.
type ItemTypeUpdate struct {
	BaseProfile *ItemTypeUpdateBaseProfile `json:"base_profile,omitempty"`
	Description *string                    `json:"description,omitempty"`
	Name        *string                    `json:"name,omitempty"`
}

// ItemTypeUpdateBaseProfile defines model for ItemTypeUpdate.BaseProfile.
type ItemTypeUpdateBaseProfile string

// ItemUpdate defines model for ItemUpdate.
type ItemUpdate struct {
	// Attributes Dynamic per-item values keyed by item type field definitions
	Attributes         *map[string]interface{}       `json:"attributes,omitempty"`
	DefaultCarryStatus *ItemUpdateDefaultCarryStatus `json:"default_carry_status,omitempty"`
	DefaultQuantity    *int                          `json:"default_quantity,omitempty"`
	Description        *string                       `json:"description,omitempty"`
	ImageBlob          *[]byte                       `json:"image_blob,omitempty"`
	ImageHeightPx      *int                          `json:"image_height_px,omitempty"`
	ImageMimeType      *string                       `json:"image_mime_type,omitempty"`
	ImageSizeBytes     *int                          `json:"image_size_bytes,omitempty"`
	ImageWidthPx       *int                          `json:"image_width_px,omitempty"`
	IsActive           *bool                         `json:"is_active,omitempty"`
	IsDefault          *bool                         `json:"is_default,omitempty"`
	ManufacturerId     *openapi_types.UUID           `json:"manufacturer_id,omitempty"`
	Name               *string                       `json:"name,omitempty"`
	SourceUrl          *string                       `json:"source_url,omitempty"`
	Type               *string                       `json:"type,omitempty"`
	Value              *float32                      `json:"value,omitempty"`
	VolumeMl           *float32                      `json:"volume_ml,omitempty"`
	WeightGrams        *float32                      `json:"weight_grams,omitempty"`
}

// ItemUpdateDefaultCarryStatus defines model for ItemUpdate.DefaultCarryStatus.
type ItemUpdateDefaultCarryStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// Manufacturer defines model for Manufacturer.
type Manufacturer struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	UpdatedAt time.Time          `json:"updated_at"`
	Website   *string            `json:"website,omitempty"`
}

// ManufacturerCreate defines model for ManufacturerCreate.
type ManufacturerCreate struct {
	Name    string  `json:"name"`
	Website *string `json:"website,omitempty"`
}

// ManufacturerUpdate defines model for ManufacturerUpdate.
type ManufacturerUpdate struct {
	Name    *string `json:"name,omitempty"`
	Website *string `json:"website,omitempty"`
}

// Pack defines model for Pack.
type Pack struct {
	CreatedAt time.Time           `json:"created_at"`
	Id        openapi_types.UUID  `json:"id"`
	Name      string              `json:"name"`
	PersonId  *openapi_types.UUID `json:"person_id,omitempty"`
	TripType  PackTripType        `json:"trip_type"`
	UpdatedAt time.Time           `json:"updated_at"`
}

// PackTripType defines model for Pack.TripType.
type PackTripType string

// PackCreate defines model for PackCreate.
type PackCreate struct {
	Name     string              `json:"name"`
	PersonId *openapi_types.UUID `json:"person_id,omitempty"`
	TripType PackCreateTripType  `json:"trip_type"`
}

// PackCreateTripType defines model for PackCreate.TripType.
type PackCreateTripType string

// PackItemCreate defines model for PackItemCreate.
type PackItemCreate struct {
	CarryStatus PackItemCreateCarryStatus `json:"carry_status"`
	ItemId      openapi_types.UUID        `json:"item_id"`
	Quantity    float32                   `json:"quantity"`
}

// PackItemCreateCarryStatus defines model for PackItemCreate.CarryStatus.
type PackItemCreateCarryStatus string

// PackItemUpdate defines model for PackItemUpdate.
type PackItemUpdate struct {
	CarryStatus *PackItemUpdateCarryStatus `json:"carry_status,omitempty"`
	Quantity    *float32                   `json:"quantity,omitempty"`
}

// PackItemUpdateCarryStatus defines model for PackItemUpdate.CarryStatus.
type PackItemUpdateCarryStatus string

// PackItemWithDetails defines model for PackItemWithDetails.
type PackItemWithDetails struct {
	CarryStatus PackItemWithDetailsCarryStatus `json:"carry_status"`
	Item        Item                           `json:"item"`
	ItemId      openapi_types.UUID             `json:"item_id"`
	Quantity    float32                        `json:"quantity"`
}

// PackItemWithDetailsCarryStatus defines model for PackItemWithDetails.CarryStatus.
type PackItemWithDetailsCarryStatus string

// PackSetCreate defines model for PackSetCreate.
type PackSetCreate struct {
	SetId openapi_types.UUID `json:"set_id"`
}

// PackUpdate defines model for PackUpdate.
type PackUpdate struct {
	Name     *string             `json:"name,omitempty"`
	PersonId *openapi_types.UUID `json:"person_id,omitempty"`
	TripType *PackUpdateTripType `json:"trip_type,omitempty"`
}

// PackUpdateTripType defines model for PackUpdate.TripType.
type PackUpdateTripType string

// Person defines model for Person.
type Person struct {
	Birthdate         *openapi_types.Date      `json:"birthdate,omitempty"`
	BodyWeightGrams   *float32                 `json:"body_weight_grams,omitempty"`
	ConditioningLevel *PersonConditioningLevel `json:"conditioning_level,omitempty"`
	CreatedAt         time.Time                `json:"created_at"`
	Gender            *PersonGender            `json:"gender,omitempty"`
	Id                openapi_types.UUID       `json:"id"`
	Name              string                   `json:"name"`
	UpdatedAt         time.Time                `json:"updated_at"`
}

// PersonConditioningLevel defines model for Person.ConditioningLevel.
type PersonConditioningLevel string

// PersonGender defines model for Person.Gender.
type PersonGender string

// PersonCreate defines model for PersonCreate.
type PersonCreate struct {
	Birthdate         *openapi_types.Date            `json:"birthdate,omitempty"`
	BodyWeightGrams   *float32                       `json:"body_weight_grams,omitempty"`
	ConditioningLevel *PersonCreateConditioningLevel `json:"conditioning_level,omitempty"`
	Gender            *PersonCreateGender            `json:"gender,omitempty"`
	Name              string                         `json:"name"`
}

// PersonCreateConditioningLevel defines model for PersonCreate.ConditioningLevel.
type PersonCreateConditioningLevel string

// PersonCreateGender defines model for PersonCreate.Gender.
type PersonCreateGender string

// PersonUpdate defines model for PersonUpdate.
type PersonUpdate struct {
	Birthdate         *openapi_types.Date            `json:"birthdate,omitempty"`
	BodyWeightGrams   *float32                       `json:"body_weight_grams,omitempty"`
	ConditioningLevel *PersonUpdateConditioningLevel `json:"conditioning_level,omitempty"`
	Gender            *PersonUpdateGender            `json:"gender,omitempty"`
	Name              *string                        `json:"name,omitempty"`
}

// PersonUpdateConditioningLevel defines model for PersonUpdate.ConditioningLevel.
type PersonUpdateConditioningLevel string

// PersonUpdateGender defines model for PersonUpdate.Gender.
type PersonUpdateGender string

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// SetItemCreate defines model for SetItemCreate.
type SetItemCreate struct {
	ItemId    openapi_types.UUID `json:"item_id"`
	Notes     *string            `json:"notes,omitempty"`
	Quantity  float32            `json:"quantity"`
	SortOrder *int               `json:"sort_order,omitempty"`
}

// SetItemUpdate defines model for SetItemUpdate.
type SetItemUpdate struct {
	Notes     *string  `json:"notes,omitempty"`
	Quantity  *float32 `json:"quantity,omitempty"`
	SortOrder *int     `json:"sort_order,omitempty"`
}

// SetItemWithDetails defines model for SetItemWithDetails.
type SetItemWithDetails struct {
	Item      Item               `json:"item"`
	ItemId    openapi_types.UUID `json:"item_id"`
	Notes     *string            `json:"notes,omitempty"`
	Quantity  float32            `json:"quantity"`
	SortOrder *int               `json:"sort_order,omitempty"`
}

// Settings defines model for Settings.
type Settings struct {
	Currency        SettingsCurrency        `json:"currency"`
	DistanceUnit    SettingsDistanceUnit    `json:"distance_unit"`
	Id              int                     `json:"id"`
	TemperatureUnit SettingsTemperatureUnit `json:"temperature_unit"`
	VolumeUnit      SettingsVolumeUnit      `json:"volume_unit"`
	WeightUnit      SettingsWeightUnit      `json:"weight_unit"`
}

// SettingsCurrency defines model for Settings.Currency.
type SettingsCurrency string

// SettingsDistanceUnit defines model for Settings.DistanceUnit.
type SettingsDistanceUnit string

// SettingsTemperatureUnit defines model for Settings.TemperatureUnit.
type SettingsTemperatureUnit string

// SettingsVolumeUnit defines model for Settings.VolumeUnit.
type SettingsVolumeUnit string

// SettingsWeightUnit defines model for Settings.WeightUnit.
type SettingsWeightUnit string

// SettingsUpdate defines model for SettingsUpdate.
type SettingsUpdate struct {
	Currency        *SettingsUpdateCurrency        `json:"currency,omitempty"`
	DistanceUnit    *SettingsUpdateDistanceUnit    `json:"distance_unit,omitempty"`
	TemperatureUnit *SettingsUpdateTemperatureUnit `json:"temperature_unit,omitempty"`
	VolumeUnit      *SettingsUpdateVolumeUnit      `json:"volume_unit,omitempty"`
	WeightUnit      *SettingsUpdateWeightUnit      `json:"weight_unit,omitempty"`
}

// SettingsUpdateCurrency defines model for SettingsUpdate.Currency.
type SettingsUpdateCurrency string

// SettingsUpdateDistanceUnit defines model for SettingsUpdate.DistanceUnit.
type SettingsUpdateDistanceUnit string

// SettingsUpdateTemperatureUnit defines model for SettingsUpdate.TemperatureUnit.
type SettingsUpdateTemperatureUnit string

// SettingsUpdateVolumeUnit defines model for SettingsUpdate.VolumeUnit.
type SettingsUpdateVolumeUnit string

// SettingsUpdateWeightUnit defines model for SettingsUpdate.WeightUnit.
type SettingsUpdateWeightUnit string

// StartFreshRequest defines model for StartFreshRequest.
type StartFreshRequest struct {
	Password string `json:"password"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken  string `json:"access_token"`
	ExpiresIn    int    `json:"expires_in"`
	RefreshToken string `json:"refresh_token"`
	TokenType    string `json:"token_type"`
}

// BadRequest defines model for BadRequest.
type BadRequest struct {
	Error string `json:"error"`
}

// NotFound defines model for NotFound.
type NotFound struct {
	Error string `json:"error"`
}

// Unauthorized defines model for Unauthorized.
type Unauthorized struct {
	Error string `json:"error"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// AuthLoginJSONRequestBody defines body for AuthLogin for application/json ContentType.
type AuthLoginJSONRequestBody = LoginRequest

// AuthRefreshJSONRequestBody defines body for AuthRefresh for application/json ContentType.
type AuthRefreshJSONRequestBody = RefreshRequest

// CreateItemTypeJSONRequestBody defines body for CreateItemType for application/json ContentType.
type CreateItemTypeJSONRequestBody = ItemTypeCreate

// UpdateItemTypeJSONRequestBody defines body for UpdateItemType for application/json ContentType.
type UpdateItemTypeJSONRequestBody = ItemTypeUpdate

// ReplaceItemTypeFieldsJSONRequestBody defines body for ReplaceItemTypeFields for application/json ContentType.
type ReplaceItemTypeFieldsJSONRequestBody = ItemTypeFieldsReplace

// CreateItemJSONRequestBody defines body for CreateItem for application/json ContentType.
type CreateItemJSONRequestBody = ItemCreate

// UpdateItemJSONRequestBody defines body for UpdateItem for application/json ContentType.
type UpdateItemJSONRequestBody = ItemUpdate

// CreateManufacturerJSONRequestBody defines body for CreateManufacturer for application/json ContentType.
type CreateManufacturerJSONRequestBody = ManufacturerCreate

// UpdateManufacturerJSONRequestBody defines body for UpdateManufacturer for application/json ContentType.
type UpdateManufacturerJSONRequestBody = ManufacturerUpdate

// CreatePackJSONRequestBody defines body for CreatePack for application/json ContentType.
type CreatePackJSONRequestBody = PackCreate

// UpdatePackJSONRequestBody defines body for UpdatePack for application/json ContentType.
type UpdatePackJSONRequestBody = PackUpdate

// AddPackItemJSONRequestBody defines body for AddPackItem for application/json ContentType.
type AddPackItemJSONRequestBody = PackItemCreate

// UpdatePackItemJSONRequestBody defines body for UpdatePackItem for application/json ContentType.
type UpdatePackItemJSONRequestBody = PackItemUpdate

// AddPackSetJSONRequestBody defines body for AddPackSet for application/json ContentType.
type AddPackSetJSONRequestBody = PackSetCreate

// CreatePersonJSONRequestBody defines body for CreatePerson for application/json ContentType.
type CreatePersonJSONRequestBody = PersonCreate

// UpdatePersonJSONRequestBody defines body for UpdatePerson for application/json ContentType.
type UpdatePersonJSONRequestBody = PersonUpdate

// CreateSetJSONRequestBody defines body for CreateSet for application/json ContentType.
type CreateSetJSONRequestBody = ItemSetCreate

// UpdateSetJSONRequestBody defines body for UpdateSet for application/json ContentType.
type UpdateSetJSONRequestBody = ItemSetUpdate

// AddSetItemJSONRequestBody defines body for AddSetItem for application/json ContentType.
type AddSetItemJSONRequestBody = SetItemCreate

// UpdateSetItemJSONRequestBody defines body for UpdateSetItem for application/json ContentType.
type UpdateSetItemJSONRequestBody = SetItemUpdate

// UpdateSettingsJSONRequestBody defines body for UpdateSettings for application/json ContentType.
type UpdateSettingsJSONRequestBody = SettingsUpdate

// StartFreshJSONRequestBody defines body for StartFresh for application/json ContentType.
type StartFreshJSONRequestBody = StartFreshRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with app credentials
	// (POST /api/v1/auth/login)
	AuthLogin(w http.ResponseWriter, r *http.Request)
	// Logout current session
	// (POST /api/v1/auth/logout)
	AuthLogout(w http.ResponseWriter, r *http.Request)
	// Refresh JWT tokens
	// (POST /api/v1/auth/refresh)
	AuthRefresh(w http.ResponseWriter, r *http.Request)
	// List all item types
	// (GET /api/v1/item-types)
	ListItemTypes(w http.ResponseWriter, r *http.Request)
	// Create a new item type
	// (POST /api/v1/item-types)
	CreateItemType(w http.ResponseWriter, r *http.Request)
	// Delete item type
	// (DELETE /api/v1/item-types/{typeId})
	DeleteItemType(w http.ResponseWriter, r *http.Request, typeId string)
	// Get item type by ID
	// (GET /api/v1/item-types/{typeId})
	GetItemType(w http.ResponseWriter, r *http.Request, typeId string)
	// Update item type
	// (PATCH /api/v1/item-types/{typeId})
	UpdateItemType(w http.ResponseWriter, r *http.Request, typeId string)
	// List field definitions for an item type
	// (GET /api/v1/item-types/{typeId}/fields)
	ListItemTypeFields(w http.ResponseWriter, r *http.Request, typeId string)
	// Replace field definitions for an item type
	// (PUT /api/v1/item-types/{typeId}/fields)
	ReplaceItemTypeFields(w http.ResponseWriter, r *http.Request, typeId string)
	// List all items
	// (GET /api/v1/items)
	ListItems(w http.ResponseWriter, r *http.Request)
	// Create a new item
	// (POST /api/v1/items)
	CreateItem(w http.ResponseWriter, r *http.Request)
	// Delete item
	// (DELETE /api/v1/items/{itemId})
	DeleteItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Get item by ID
	// (GET /api/v1/items/{itemId})
	GetItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Update item
	// (PATCH /api/v1/items/{itemId})
	UpdateItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// List all manufacturers
	// (GET /api/v1/manufacturers)
	ListManufacturers(w http.ResponseWriter, r *http.Request)
	// Create a new manufacturer
	// (POST /api/v1/manufacturers)
	CreateManufacturer(w http.ResponseWriter, r *http.Request)
	// Delete manufacturer
	// (DELETE /api/v1/manufacturers/{manufacturerId})
	DeleteManufacturer(w http.ResponseWriter, r *http.Request, manufacturerId openapi_types.UUID)
	// Get manufacturer by ID
	// (GET /api/v1/manufacturers/{manufacturerId})
	GetManufacturer(w http.ResponseWriter, r *http.Request, manufacturerId openapi_types.UUID)
	// Update manufacturer
	// (PATCH /api/v1/manufacturers/{manufacturerId})
	UpdateManufacturer(w http.ResponseWriter, r *http.Request, manufacturerId openapi_types.UUID)
	// List all packs
	// (GET /api/v1/packs)
	ListPacks(w http.ResponseWriter, r *http.Request)
	// Create a new pack
	// (POST /api/v1/packs)
	CreatePack(w http.ResponseWriter, r *http.Request)
	// Delete pack
	// (DELETE /api/v1/packs/{packId})
	DeletePack(w http.ResponseWriter, r *http.Request, packId openapi_types.UUID)
	// Get pack by ID
	// (GET /api/v1/packs/{packId})
	GetPack(w http.ResponseWriter, r *http.Request, packId openapi_types.UUID)
	// Update pack
	// (PATCH /api/v1/packs/{packId})
	UpdatePack(w http.ResponseWriter, r *http.Request, packId openapi_types.UUID)
	// List items in a pack
	// (GET /api/v1/packs/{packId}/items)
	ListPackItems(w http.ResponseWriter, r *http.Request, packId openapi_types.UUID)
	// Add item to pack
	// (POST /api/v1/packs/{packId}/items)
	AddPackItem(w http.ResponseWriter, r *http.Request, packId openapi_types.UUID)
	// Remove item from pack
	// (DELETE /api/v1/packs/{packId}/items/{itemId})
	RemovePackItem(w http.ResponseWriter, r *http.Request, packId openapi_types.UUID, itemId openapi_types.UUID)
	// Update item in pack
	// (PATCH /api/v1/packs/{packId}/items/{itemId})
	UpdatePackItem(w http.ResponseWriter, r *http.Request, packId openapi_types.UUID, itemId openapi_types.UUID)
	// List sets applied to pack
	// (GET /api/v1/packs/{packId}/sets)
	ListPackSets(w http.ResponseWriter, r *http.Request, packId openapi_types.UUID)
	// Apply set to pack
	// (POST /api/v1/packs/{packId}/sets)
	AddPackSet(w http.ResponseWriter, r *http.Request, packId openapi_types.UUID)
	// Remove set from pack
	// (DELETE /api/v1/packs/{packId}/sets/{setId})
	RemovePackSet(w http.ResponseWriter, r *http.Request, packId openapi_types.UUID, setId openapi_types.UUID)
	// List all persons
	// (GET /api/v1/persons)
	ListPersons(w http.ResponseWriter, r *http.Request)
	// Create a new person
	// (POST /api/v1/persons)
	CreatePerson(w http.ResponseWriter, r *http.Request)
	// Delete person
	// (DELETE /api/v1/persons/{personId})
	DeletePerson(w http.ResponseWriter, r *http.Request, personId openapi_types.UUID)
	// Get person by ID
	// (GET /api/v1/persons/{personId})
	GetPerson(w http.ResponseWriter, r *http.Request, personId openapi_types.UUID)
	// Update person
	// (PATCH /api/v1/persons/{personId})
	UpdatePerson(w http.ResponseWriter, r *http.Request, personId openapi_types.UUID)
	// List all item sets
	// (GET /api/v1/sets)
	ListSets(w http.ResponseWriter, r *http.Request)
	// Create a new item set
	// (POST /api/v1/sets)
	CreateSet(w http.ResponseWriter, r *http.Request)
	// Delete item set
	// (DELETE /api/v1/sets/{setId})
	DeleteSet(w http.ResponseWriter, r *http.Request, setId openapi_types.UUID)
	// Get item set by ID
	// (GET /api/v1/sets/{setId})
	GetSet(w http.ResponseWriter, r *http.Request, setId openapi_types.UUID)
	// Update item set
	// (PATCH /api/v1/sets/{setId})
	UpdateSet(w http.ResponseWriter, r *http.Request, setId openapi_types.UUID)
	// List items in a set
	// (GET /api/v1/sets/{setId}/items)
	ListSetItems(w http.ResponseWriter, r *http.Request, setId openapi_types.UUID)
	// Add item to set
	// (POST /api/v1/sets/{setId}/items)
	AddSetItem(w http.ResponseWriter, r *http.Request, setId openapi_types.UUID)
	// Remove item from set
	// (DELETE /api/v1/sets/{setId}/items/{itemId})
	RemoveSetItem(w http.ResponseWriter, r *http.Request, setId openapi_types.UUID, itemId openapi_types.UUID)
	// Update item in set
	// (PATCH /api/v1/sets/{setId}/items/{itemId})
	UpdateSetItem(w http.ResponseWriter, r *http.Request, setId openapi_types.UUID, itemId openapi_types.UUID)
	// Get current settings
	// (GET /api/v1/settings)
	GetSettings(w http.ResponseWriter, r *http.Request)
	// Update settings
	// (PATCH /api/v1/settings)
	UpdateSettings(w http.ResponseWriter, r *http.Request)
	// Permanently delete all app data and reset defaults
	// (POST /api/v1/settings/start-fresh)
	StartFresh(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) AuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthLogout operation middleware
func (siw *ServerInterfaceWrapper) AuthLogout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthRefresh operation middleware
func (siw *ServerInterfaceWrapper) AuthRefresh(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthRefresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListItemTypes operation middleware
func (siw *ServerInterfaceWrapper) ListItemTypes(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListItemTypes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateItemType operation middleware
func (siw *ServerInterfaceWrapper) CreateItemType(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateItemType(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteItemType operation middleware
func (siw *ServerInterfaceWrapper) DeleteItemType(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "typeId" -------------
	var typeId string

	err = runtime.BindStyledParameterWithOptions("simple", "typeId", r.PathValue("typeId"), &typeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "typeId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteItemType(w, r, typeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetItemType operation middleware
func (siw *ServerInterfaceWrapper) GetItemType(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "typeId" -------------
	var typeId string

	err = runtime.BindStyledParameterWithOptions("simple", "typeId", r.PathValue("typeId"), &typeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "typeId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetItemType(w, r, typeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateItemType operation middleware
func (siw *ServerInterfaceWrapper) UpdateItemType(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "typeId" -------------
	var typeId string

	err = runtime.BindStyledParameterWithOptions("simple", "typeId", r.PathValue("typeId"), &typeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "typeId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateItemType(w, r, typeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListItemTypeFields operation middleware
func (siw *ServerInterfaceWrapper) ListItemTypeFields(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "typeId" -------------
	var typeId string

	err = runtime.BindStyledParameterWithOptions("simple", "typeId", r.PathValue("typeId"), &typeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "typeId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListItemTypeFields(w, r, typeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReplaceItemTypeFields operation middleware
func (siw *ServerInterfaceWrapper) ReplaceItemTypeFields(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "typeId" -------------
	var typeId string

	err = runtime.BindStyledParameterWithOptions("simple", "typeId", r.PathValue("typeId"), &typeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "typeId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReplaceItemTypeFields(w, r, typeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListItems operation middleware
func (siw *ServerInterfaceWrapper) ListItems(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListItems(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateItem operation middleware
func (siw *ServerInterfaceWrapper) CreateItem(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateItem(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetItem operation middleware
func (siw *ServerInterfaceWrapper) GetItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListManufacturers operation middleware
func (siw *ServerInterfaceWrapper) ListManufacturers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListManufacturers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateManufacturer operation middleware
func (siw *ServerInterfaceWrapper) CreateManufacturer(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateManufacturer(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteManufacturer operation middleware
func (siw *ServerInterfaceWrapper) DeleteManufacturer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "manufacturerId" -------------
	var manufacturerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "manufacturerId", r.PathValue("manufacturerId"), &manufacturerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "manufacturerId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteManufacturer(w, r, manufacturerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetManufacturer operation middleware
func (siw *ServerInterfaceWrapper) GetManufacturer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "manufacturerId" -------------
	var manufacturerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "manufacturerId", r.PathValue("manufacturerId"), &manufacturerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "manufacturerId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetManufacturer(w, r, manufacturerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateManufacturer operation middleware
func (siw *ServerInterfaceWrapper) UpdateManufacturer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "manufacturerId" -------------
	var manufacturerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "manufacturerId", r.PathValue("manufacturerId"), &manufacturerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "manufacturerId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateManufacturer(w, r, manufacturerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPacks operation middleware
func (siw *ServerInterfaceWrapper) ListPacks(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPacks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePack operation middleware
func (siw *ServerInterfaceWrapper) CreatePack(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePack(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePack operation middleware
func (siw *ServerInterfaceWrapper) DeletePack(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "packId" -------------
	var packId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "packId", r.PathValue("packId"), &packId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "packId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePack(w, r, packId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPack operation middleware
func (siw *ServerInterfaceWrapper) GetPack(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "packId" -------------
	var packId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "packId", r.PathValue("packId"), &packId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "packId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPack(w, r, packId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePack operation middleware
func (siw *ServerInterfaceWrapper) UpdatePack(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "packId" -------------
	var packId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "packId", r.PathValue("packId"), &packId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "packId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePack(w, r, packId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPackItems operation middleware
func (siw *ServerInterfaceWrapper) ListPackItems(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "packId" -------------
	var packId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "packId", r.PathValue("packId"), &packId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "packId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPackItems(w, r, packId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddPackItem operation middleware
func (siw *ServerInterfaceWrapper) AddPackItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "packId" -------------
	var packId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "packId", r.PathValue("packId"), &packId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "packId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddPackItem(w, r, packId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemovePackItem operation middleware
func (siw *ServerInterfaceWrapper) RemovePackItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "packId" -------------
	var packId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "packId", r.PathValue("packId"), &packId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "packId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemovePackItem(w, r, packId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePackItem operation middleware
func (siw *ServerInterfaceWrapper) UpdatePackItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "packId" -------------
	var packId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "packId", r.PathValue("packId"), &packId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "packId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePackItem(w, r, packId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPackSets operation middleware
func (siw *ServerInterfaceWrapper) ListPackSets(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "packId" -------------
	var packId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "packId", r.PathValue("packId"), &packId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "packId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPackSets(w, r, packId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddPackSet operation middleware
func (siw *ServerInterfaceWrapper) AddPackSet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "packId" -------------
	var packId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "packId", r.PathValue("packId"), &packId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "packId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddPackSet(w, r, packId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemovePackSet operation middleware
func (siw *ServerInterfaceWrapper) RemovePackSet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "packId" -------------
	var packId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "packId", r.PathValue("packId"), &packId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "packId", Err: err})
		return
	}

	// ------------- Path parameter "setId" -------------
	var setId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "setId", r.PathValue("setId"), &setId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "setId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemovePackSet(w, r, packId, setId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPersons operation middleware
func (siw *ServerInterfaceWrapper) ListPersons(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPersons(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePerson operation middleware
func (siw *ServerInterfaceWrapper) CreatePerson(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePerson(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePerson operation middleware
func (siw *ServerInterfaceWrapper) DeletePerson(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "personId" -------------
	var personId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "personId", r.PathValue("personId"), &personId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "personId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePerson(w, r, personId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPerson operation middleware
func (siw *ServerInterfaceWrapper) GetPerson(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "personId" -------------
	var personId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "personId", r.PathValue("personId"), &personId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "personId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPerson(w, r, personId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePerson operation middleware
func (siw *ServerInterfaceWrapper) UpdatePerson(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "personId" -------------
	var personId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "personId", r.PathValue("personId"), &personId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "personId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePerson(w, r, personId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSets operation middleware
func (siw *ServerInterfaceWrapper) ListSets(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSets(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSet operation middleware
func (siw *ServerInterfaceWrapper) CreateSet(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSet operation middleware
func (siw *ServerInterfaceWrapper) DeleteSet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "setId" -------------
	var setId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "setId", r.PathValue("setId"), &setId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "setId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSet(w, r, setId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSet operation middleware
func (siw *ServerInterfaceWrapper) GetSet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "setId" -------------
	var setId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "setId", r.PathValue("setId"), &setId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "setId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSet(w, r, setId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSet operation middleware
func (siw *ServerInterfaceWrapper) UpdateSet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "setId" -------------
	var setId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "setId", r.PathValue("setId"), &setId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "setId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSet(w, r, setId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSetItems operation middleware
func (siw *ServerInterfaceWrapper) ListSetItems(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "setId" -------------
	var setId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "setId", r.PathValue("setId"), &setId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "setId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSetItems(w, r, setId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddSetItem operation middleware
func (siw *ServerInterfaceWrapper) AddSetItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "setId" -------------
	var setId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "setId", r.PathValue("setId"), &setId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "setId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddSetItem(w, r, setId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveSetItem operation middleware
func (siw *ServerInterfaceWrapper) RemoveSetItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "setId" -------------
	var setId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "setId", r.PathValue("setId"), &setId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "setId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveSetItem(w, r, setId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSetItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateSetItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "setId" -------------
	var setId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "setId", r.PathValue("setId"), &setId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "setId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSetItem(w, r, setId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSettings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateSettings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartFresh operation middleware
func (siw *ServerInterfaceWrapper) StartFresh(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartFresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/auth/login", wrapper.AuthLogin)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/auth/logout", wrapper.AuthLogout)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/auth/refresh", wrapper.AuthRefresh)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/item-types", wrapper.ListItemTypes)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/item-types", wrapper.CreateItemType)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/item-types/{typeId}", wrapper.DeleteItemType)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/item-types/{typeId}", wrapper.GetItemType)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/item-types/{typeId}", wrapper.UpdateItemType)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/item-types/{typeId}/fields", wrapper.ListItemTypeFields)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/api/v1/item-types/{typeId}/fields", wrapper.ReplaceItemTypeFields)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/items", wrapper.ListItems)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/items", wrapper.CreateItem)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/items/{itemId}", wrapper.DeleteItem)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/items/{itemId}", wrapper.GetItem)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/items/{itemId}", wrapper.UpdateItem)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/manufacturers", wrapper.ListManufacturers)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/manufacturers", wrapper.CreateManufacturer)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/manufacturers/{manufacturerId}", wrapper.DeleteManufacturer)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/manufacturers/{manufacturerId}", wrapper.GetManufacturer)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/manufacturers/{manufacturerId}", wrapper.UpdateManufacturer)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/packs", wrapper.ListPacks)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/packs", wrapper.CreatePack)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/packs/{packId}", wrapper.DeletePack)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/packs/{packId}", wrapper.GetPack)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/packs/{packId}", wrapper.UpdatePack)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/packs/{packId}/items", wrapper.ListPackItems)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/packs/{packId}/items", wrapper.AddPackItem)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/packs/{packId}/items/{itemId}", wrapper.RemovePackItem)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/packs/{packId}/items/{itemId}", wrapper.UpdatePackItem)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/packs/{packId}/sets", wrapper.ListPackSets)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/packs/{packId}/sets", wrapper.AddPackSet)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/packs/{packId}/sets/{setId}", wrapper.RemovePackSet)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/persons", wrapper.ListPersons)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/persons", wrapper.CreatePerson)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/persons/{personId}", wrapper.DeletePerson)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/persons/{personId}", wrapper.GetPerson)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/persons/{personId}", wrapper.UpdatePerson)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/sets", wrapper.ListSets)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/sets", wrapper.CreateSet)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/sets/{setId}", wrapper.DeleteSet)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/sets/{setId}", wrapper.GetSet)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/sets/{setId}", wrapper.UpdateSet)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/sets/{setId}/items", wrapper.ListSetItems)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/sets/{setId}/items", wrapper.AddSetItem)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/sets/{setId}/items/{itemId}", wrapper.RemoveSetItem)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/sets/{setId}/items/{itemId}", wrapper.UpdateSetItem)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/settings", wrapper.GetSettings)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/settings", wrapper.UpdateSettings)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/settings/start-fresh", wrapper.StartFresh)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.HealthCheck)

	return m
}
