{{- if not .Values.backend.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-backend" (include "overpacked-app.fullname" .) }}
  labels:
    {{- include "overpacked-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.backend.secretKeys.appUsername }}: {{ .Values.backend.auth.username | quote }}
  {{ .Values.backend.secretKeys.appPassword }}: {{ .Values.backend.auth.password | quote }}
  {{ .Values.backend.secretKeys.jwtSecret }}: {{ .Values.backend.auth.jwtSecret | quote }}
  {{- if eq .Values.database.mode "cloudnativepg" }}
  {{ .Values.backend.secretKeys.databaseUrl }}: {{ printf "postgres://%s:%s@%s:5432/%s?sslmode=disable" .Values.database.auth.username .Values.database.auth.password (include "overpacked-app.db.rwService" .) .Values.database.auth.database | quote }}
  {{- else }}
  {{ .Values.backend.secretKeys.databaseUrl }}: {{ include "overpacked-app.externalDatabaseUrl" . | quote }}
  {{- end }}
{{- end }}
