{{- if eq .Values.database.mode "cloudnativepg" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db-auth" (include "overpacked-app.fullname" .) }}
  labels:
    {{- include "overpacked-app.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.database.auth.username | quote }}
  password: {{ required "database.auth.password is required" .Values.database.auth.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db-superuser" (include "overpacked-app.fullname" .) }}
  labels:
    {{- include "overpacked-app.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.database.superuser.username | quote }}
  password: {{ required "database.superuser.password is required" .Values.database.superuser.password | quote }}
{{- end }}
