{{- if .Values.frontend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "overpacked-app.frontend.fullname" . }}
  labels:
    {{- include "overpacked-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  minAvailable: {{ .Values.frontend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "overpacked-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
{{- end }}
