name-template: '$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Breaking Changes'
    labels:
      - 'breaking-change'
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'refactor'
      - 'dependencies'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\<*_&'

template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
      - 'breaking-change'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'fix'
      - 'chore'
      - 'refactor'
      - 'dependencies'
  default: patch

exclude-labels:
  - 'skip-changelog'
