/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with app credentials */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh JWT tokens */
        post: operations["authRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout current session */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current settings */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update settings */
        patch: operations["updateSettings"];
        trace?: never;
    };
    "/api/v1/settings/start-fresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Permanently delete all app data and reset defaults */
        post: operations["startFresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/persons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all persons */
        get: operations["listPersons"];
        put?: never;
        /** Create a new person */
        post: operations["createPerson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/persons/{personId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get person by ID */
        get: operations["getPerson"];
        put?: never;
        post?: never;
        /** Delete person */
        delete: operations["deletePerson"];
        options?: never;
        head?: never;
        /** Update person */
        patch: operations["updatePerson"];
        trace?: never;
    };
    "/api/v1/manufacturers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all manufacturers */
        get: operations["listManufacturers"];
        put?: never;
        /** Create a new manufacturer */
        post: operations["createManufacturer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/manufacturers/{manufacturerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get manufacturer by ID */
        get: operations["getManufacturer"];
        put?: never;
        post?: never;
        /** Delete manufacturer */
        delete: operations["deleteManufacturer"];
        options?: never;
        head?: never;
        /** Update manufacturer */
        patch: operations["updateManufacturer"];
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Global fuzzy search across entities */
        get: operations["searchGlobal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all items */
        get: operations["listItems"];
        put?: never;
        /** Create a new item */
        post: operations["createItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get item by ID */
        get: operations["getItem"];
        put?: never;
        post?: never;
        /** Delete item */
        delete: operations["deleteItem"];
        options?: never;
        head?: never;
        /** Update item */
        patch: operations["updateItem"];
        trace?: never;
    };
    "/api/v1/item-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all item types */
        get: operations["listItemTypes"];
        put?: never;
        /** Create a new item type */
        post: operations["createItemType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/item-types/{typeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get item type by ID */
        get: operations["getItemType"];
        put?: never;
        post?: never;
        /** Delete item type */
        delete: operations["deleteItemType"];
        options?: never;
        head?: never;
        /** Update item type */
        patch: operations["updateItemType"];
        trace?: never;
    };
    "/api/v1/item-types/{typeId}/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List field definitions for an item type */
        get: operations["listItemTypeFields"];
        /** Replace field definitions for an item type */
        put: operations["replaceItemTypeFields"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all labels */
        get: operations["listLabels"];
        put?: never;
        /** Create a new label */
        post: operations["createLabel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/labels/{labelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get label by ID */
        get: operations["getLabel"];
        put?: never;
        post?: never;
        /** Delete label */
        delete: operations["deleteLabel"];
        options?: never;
        head?: never;
        /** Update label */
        patch: operations["updateLabel"];
        trace?: never;
    };
    "/api/v1/items/{itemId}/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List labels for an item */
        get: operations["listItemLabels"];
        put?: never;
        /** Add label to item */
        post: operations["addItemLabel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{itemId}/labels/{labelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove label from item */
        delete: operations["removeItemLabel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all item sets */
        get: operations["listSets"];
        put?: never;
        /** Create a new item set */
        post: operations["createSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sets/{setId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get item set by ID */
        get: operations["getSet"];
        put?: never;
        post?: never;
        /** Delete item set */
        delete: operations["deleteSet"];
        options?: never;
        head?: never;
        /** Update item set */
        patch: operations["updateSet"];
        trace?: never;
    };
    "/api/v1/sets/{setId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List items in a set */
        get: operations["listSetItems"];
        put?: never;
        /** Add item to set */
        post: operations["addSetItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sets/{setId}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove item from set */
        delete: operations["removeSetItem"];
        options?: never;
        head?: never;
        /** Update item in set */
        patch: operations["updateSetItem"];
        trace?: never;
    };
    "/api/v1/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all trips */
        get: operations["listTrips"];
        put?: never;
        /** Create a new trip */
        post: operations["createTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/route-preview/{service}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch route link preview metadata
         * @description Fetches Open Graph preview metadata (image, title) for a public route share link. The service is supplied in the path. komoot and strava requests are restricted to their official hosts; wanderer accepts any public self-hosted instance (requests resolving to private or loopback addresses are rejected).
         */
        get: operations["getTripRoutePreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{tripId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get trip by ID with full nested data
         * @description Returns complete trip details including all persons, their packs, pack items, and direct person items in a single call
         */
        get: operations["getTripById"];
        put?: never;
        post?: never;
        /** Delete trip */
        delete: operations["deleteTrip"];
        options?: never;
        head?: never;
        /** Update trip */
        patch: operations["updateTrip"];
        trace?: never;
    };
    "/api/v1/trips/{tripId}/persons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add person to trip */
        post: operations["addTripPerson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{tripId}/persons/{personId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove person from trip */
        delete: operations["removeTripPerson"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{tripId}/persons/{personId}/packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create pack for person in trip
         * @description Creates a new pack and assigns it to the person in the trip context
         */
        post: operations["addTripPersonPack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{tripId}/persons/{personId}/packs/{packId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove pack from person in trip */
        delete: operations["removeTripPersonPack"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{tripId}/persons/{personId}/packs/{packId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add item to pack for a person in a trip */
        post: operations["addTripPersonPackItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{tripId}/persons/{personId}/packs/{packId}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove item from pack for a person in a trip */
        delete: operations["removeTripPersonPackItem"];
        options?: never;
        head?: never;
        /** Update item in pack for a person in a trip */
        patch: operations["updateTripPersonPackItem"];
        trace?: never;
    };
    "/api/v1/trips/{tripId}/persons/{personId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign item to person in trip */
        post: operations["addTripPersonItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{tripId}/persons/{personId}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove item from person in trip */
        delete: operations["removeTripPersonItem"];
        options?: never;
        head?: never;
        /** Update item for person in trip */
        patch: operations["updateTripPersonItem"];
        trace?: never;
    };
    "/api/v1/packing-lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all packing lists */
        get: operations["listPackingLists"];
        put?: never;
        /** Create a new packing list */
        post: operations["createPackingList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/packing-lists/{listId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get packing list by ID */
        get: operations["getPackingListById"];
        put?: never;
        post?: never;
        /** Delete packing list */
        delete: operations["deletePackingList"];
        options?: never;
        head?: never;
        /** Update packing list */
        patch: operations["updatePackingList"];
        trace?: never;
    };
    "/api/v1/packing-lists/{listId}/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List labels for a packing list */
        get: operations["listPackingListLabels"];
        put?: never;
        /** Add label to packing list */
        post: operations["addPackingListLabel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/packing-lists/{listId}/labels/{labelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove label from packing list */
        delete: operations["removePackingListLabel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            username: string;
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        TokenResponse: {
            access_token: string;
            refresh_token: string;
            token_type: string;
            expires_in: number;
        };
        /** @enum {string} */
        SearchEntityType: "item" | "set" | "packing_list" | "person" | "manufacturer" | "trip";
        SearchResult: {
            entity_type: components["schemas"]["SearchEntityType"];
            id: string;
            title: string;
            subtitle?: string | null;
            /** Format: double */
            score: number;
        };
        Settings: {
            id: number;
            /** @enum {string} */
            weight_unit: "g" | "oz";
            /** @enum {string} */
            distance_unit: "km" | "mi";
            /** @enum {string} */
            temperature_unit: "c" | "f";
            /** @enum {string} */
            volume_unit: "ml" | "fl_oz";
            /** @enum {string} */
            currency: "usd" | "eur";
        };
        SettingsUpdate: {
            /** @enum {string} */
            weight_unit?: "g" | "oz";
            /** @enum {string} */
            distance_unit?: "km" | "mi";
            /** @enum {string} */
            temperature_unit?: "c" | "f";
            /** @enum {string} */
            volume_unit?: "ml" | "fl_oz";
            /** @enum {string} */
            currency?: "usd" | "eur";
        };
        StartFreshRequest: {
            password: string;
        };
        Person: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string|null} */
            gender?: "male" | "female" | "other" | null;
            /** Format: date */
            birthdate?: string | null;
            /** Format: float */
            body_weight_grams?: number;
            /** @enum {string|null} */
            conditioning_level?: "sedentary" | "average" | "athletic" | "military" | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PersonCreate: {
            name: string;
            /** @enum {string} */
            gender?: "male" | "female" | "other";
            /** Format: date */
            birthdate?: string;
            /** Format: float */
            body_weight_grams?: number;
            /** @enum {string} */
            conditioning_level?: "sedentary" | "average" | "athletic" | "military";
        };
        PersonUpdate: {
            name?: string;
            /** @enum {string} */
            gender?: "male" | "female" | "other";
            /** Format: date */
            birthdate?: string;
            /** Format: float */
            body_weight_grams?: number;
            /** @enum {string} */
            conditioning_level?: "sedentary" | "average" | "athletic" | "military";
        };
        Manufacturer: {
            /** Format: uuid */
            id: string;
            name: string;
            website?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ManufacturerCreate: {
            name: string;
            website?: string;
        };
        ManufacturerUpdate: {
            name?: string;
            website?: string;
        };
        ItemType: {
            /** @description Machine key for the item type, e.g. consumable or my_power_kit */
            id: string;
            name: string;
            description?: string | null;
            /** @enum {string|null} */
            base_profile?: "consumable" | "wearable" | "shelter" | "sleep" | "electronics" | null;
            is_system: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ItemTypeCreate: {
            id: string;
            name: string;
            description?: string | null;
            /** @enum {string|null} */
            base_profile?: "consumable" | "wearable" | "shelter" | "sleep" | "electronics" | null;
        };
        ItemTypeUpdate: {
            name?: string;
            description?: string | null;
            /** @enum {string|null} */
            base_profile?: "consumable" | "wearable" | "shelter" | "sleep" | "electronics" | null;
        };
        ItemTypeField: {
            /** Format: uuid */
            id: string;
            item_type_id: string;
            field_key: string;
            field_label: string;
            /** @enum {string} */
            data_type: "string" | "integer" | "number" | "boolean" | "enum";
            is_required: boolean;
            enum_options?: string[] | null;
            /** Format: float */
            min_value?: number | null;
            /** Format: float */
            max_value?: number | null;
            unit?: string | null;
            sort_order: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ItemTypeFieldInput: {
            field_key: string;
            field_label: string;
            /** @enum {string} */
            data_type: "string" | "integer" | "number" | "boolean" | "enum";
            is_required?: boolean | null;
            enum_options?: string[] | null;
            /** Format: float */
            min_value?: number | null;
            /** Format: float */
            max_value?: number | null;
            unit?: string | null;
            sort_order?: number | null;
        };
        ItemTypeFieldsReplace: {
            fields: components["schemas"]["ItemTypeFieldInput"][];
        };
        Item: components["schemas"]["ItemBase"];
        ItemBase: {
            /** Format: uuid */
            id: string;
            name: string;
            type: string;
            is_active: boolean;
            /** Format: uuid */
            manufacturer_id: string;
            description?: string | null;
            source_url?: string | null;
            value?: number | null;
            /** Format: float */
            weight_grams?: number | null;
            /** Format: float */
            volume_ml?: number | null;
            default_quantity?: number | null;
            /** @enum {string|null} */
            default_carry_status?: "packed" | "worn" | null;
            is_default?: boolean | null;
            /** Format: byte */
            image_blob?: string | null;
            image_mime_type?: string | null;
            image_size_bytes?: number | null;
            image_width_px?: number | null;
            image_height_px?: number | null;
            /** @description Dynamic per-item values keyed by item type field definitions */
            attributes?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ItemCreate: {
            name: string;
            type: string;
            is_active: boolean;
            /** Format: uuid */
            manufacturer_id: string;
            description?: string | null;
            source_url?: string | null;
            /** Format: float */
            value?: number | null;
            /** Format: float */
            weight_grams?: number | null;
            /** Format: float */
            volume_ml?: number | null;
            default_quantity?: number | null;
            /** @enum {string|null} */
            default_carry_status?: "packed" | "worn" | null;
            is_default?: boolean | null;
            /** Format: byte */
            image_blob?: string | null;
            image_mime_type?: string | null;
            image_size_bytes?: number | null;
            image_width_px?: number | null;
            image_height_px?: number | null;
            /** @description Dynamic per-item values keyed by item type field definitions */
            attributes?: {
                [key: string]: unknown;
            } | null;
        };
        ItemUpdate: {
            name?: string;
            type?: string;
            is_active?: boolean;
            /** Format: uuid */
            manufacturer_id?: string;
            description?: string | null;
            source_url?: string | null;
            /** Format: float */
            value?: number | null;
            /** Format: float */
            weight_grams?: number | null;
            /** Format: float */
            volume_ml?: number | null;
            default_quantity?: number | null;
            /** @enum {string|null} */
            default_carry_status?: "packed" | "worn" | null;
            is_default?: boolean | null;
            /** Format: byte */
            image_blob?: string | null;
            image_mime_type?: string | null;
            image_size_bytes?: number | null;
            image_width_px?: number | null;
            image_height_px?: number | null;
            /** @description Dynamic per-item values keyed by item type field definitions */
            attributes?: {
                [key: string]: unknown;
            } | null;
        };
        Label: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description Hex color code for UI display (e.g., */
            color?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        LabelCreate: {
            name: string;
            /** @description Hex color code for UI display (e.g., */
            color?: string | null;
        };
        LabelUpdate: {
            name?: string;
            /** @description Hex color code for UI display (e.g., */
            color?: string | null;
        };
        ItemLabelAdd: {
            /** Format: uuid */
            label_id: string;
        };
        ItemSet: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description Item type id used to categorize this set */
            set_category: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ItemSetCreate: {
            name: string;
            /** @description Item type id used to categorize this set */
            set_category: string;
        };
        ItemSetUpdate: {
            name?: string;
            set_category: string;
        };
        SetItem: {
            /** Format: uuid */
            item_id: string;
            /** Format: float */
            quantity: number;
            notes?: string | null;
            sort_order?: number | null;
        };
        SetItemCreate: {
            /** Format: uuid */
            item_id: string;
            /** Format: float */
            quantity: number;
            notes?: string;
            sort_order?: number;
        };
        SetItemUpdate: {
            /** Format: float */
            quantity?: number;
            notes?: string;
            sort_order?: number;
        };
        SetItemWithDetails: {
            /** Format: uuid */
            item_id: string;
            /** Format: float */
            quantity: number;
            notes?: string | null;
            sort_order?: number | null;
            item: components["schemas"]["Item"];
        };
        Pack: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            trip_type: "day_hike" | "overnight" | "multi_day" | "thru_hike";
            /** Format: uuid */
            person_id?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PackCreate: {
            name: string;
            /** @enum {string} */
            trip_type: "day_hike" | "overnight" | "multi_day" | "thru_hike";
            /** Format: uuid */
            person_id?: string;
        };
        PackUpdate: {
            name?: string;
            /** @enum {string} */
            trip_type?: "day_hike" | "overnight" | "multi_day" | "thru_hike";
            /** Format: uuid */
            person_id?: string;
        };
        PackItem: {
            /** Format: uuid */
            item_id: string;
            /** Format: float */
            quantity: number;
            /** @enum {string} */
            carry_status: "packed" | "worn";
        };
        PackItemCreate: {
            /** Format: uuid */
            item_id: string;
            /** Format: float */
            quantity: number;
            /** @enum {string} */
            carry_status: "packed" | "worn";
            notes?: string | null;
        };
        PackItemUpdate: {
            /** Format: float */
            quantity?: number;
            /** @enum {string} */
            carry_status?: "packed" | "worn";
            notes?: string | null;
        };
        PackItemWithDetails: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            item_id: string;
            /** Format: float */
            quantity: number;
            /** @enum {string} */
            carry_status: "packed" | "worn";
            notes?: string | null;
            item: components["schemas"]["Item"];
        };
        Trip: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            trip_type: "day_hike" | "overnight" | "multi_day" | "thru_hike";
            duration?: string | null;
            notes?: string | null;
            trip_komoot_url?: string | null;
            trip_strava_url?: string | null;
            trip_wanderer_url?: string | null;
            /** Format: float */
            total_distance_km?: number | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TripRoutePreview: {
            /** @enum {string} */
            service: "komoot" | "strava" | "wanderer" | "unknown";
            image_url?: string | null;
            title?: string | null;
        };
        TripWithDetails: components["schemas"]["Trip"] & {
            /** @description All persons participating in this trip with their packs and items */
            persons: components["schemas"]["TripPersonDetailsNested"][];
        };
        TripCreate: {
            name: string;
            /** @enum {string} */
            trip_type: "day_hike" | "overnight" | "multi_day" | "thru_hike";
            duration?: string;
            notes?: string;
            trip_komoot_url?: string;
            trip_strava_url?: string;
            trip_wanderer_url?: string;
            /** Format: float */
            total_distance_km?: number;
        };
        TripUpdate: {
            name?: string;
            /** @enum {string} */
            trip_type?: "day_hike" | "overnight" | "multi_day" | "thru_hike";
            duration?: string;
            notes?: string;
            trip_komoot_url?: string;
            trip_strava_url?: string;
            trip_wanderer_url?: string;
            /** Format: float */
            total_distance_km?: number;
        };
        TripPersonCreate: {
            /** Format: uuid */
            person_id: string;
        };
        TripPersonWithDetails: {
            /** Format: uuid */
            person_id: string;
            person: components["schemas"]["Person"];
        };
        TripPersonDetailsNested: {
            /**
             * Format: uuid
             * @description ID of the trip_persons junction record
             */
            trip_person_id: string;
            /** Format: uuid */
            person_id: string;
            person: components["schemas"]["Person"];
            /** @description Packs assigned to this person for the trip */
            packs: components["schemas"]["TripPersonPackDetailsNested"][];
            /** @description Items directly assigned to this person (worn or not in packs) */
            items: components["schemas"]["TripPersonItemWithDetails"][];
        };
        TripPersonPackCreate: {
            name: string;
            /** @enum {string} */
            trip_type: "day_hike" | "overnight" | "multi_day" | "thru_hike";
            notes?: string | null;
        };
        TripPersonPackWithDetails: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            trip_person_id: string;
            /** Format: uuid */
            pack_id: string;
            pack: components["schemas"]["Pack"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TripPersonPackDetailsNested: components["schemas"]["TripPersonPackWithDetails"] & {
            /** @description Items in this pack */
            items: components["schemas"]["PackItemWithDetails"][];
        };
        TripPersonItemCreate: {
            /** Format: uuid */
            item_id: string;
            quantity: number;
            /** @enum {string} */
            carry_status: "packed" | "worn";
            notes?: string;
        };
        TripPersonItemUpdate: {
            quantity?: number;
            /** @enum {string} */
            carry_status?: "packed" | "worn";
            notes?: string;
        };
        TripPersonItemWithDetails: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            trip_person_id: string;
            /** Format: uuid */
            item_id: string;
            quantity: number;
            /** @enum {string} */
            carry_status: "packed" | "worn";
            notes?: string | null;
            item: components["schemas"]["Item"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PackingList: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PackingListCreate: {
            name: string;
            description?: string;
        };
        PackingListUpdate: {
            name?: string;
            description?: string;
        };
        PackingListLabelAdd: {
            /** Format: uuid */
            label_id: string;
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: string;
                };
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: string;
                };
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authentication successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    authRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Tokens refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settings retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Settings updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    startFresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartFreshRequest"];
            };
        };
        responses: {
            /** @description Data reset completed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listPersons: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of persons */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createPerson: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonCreate"];
            };
        };
        responses: {
            /** @description Person created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getPerson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                personId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Person retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deletePerson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                personId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Person deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updatePerson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                personId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonUpdate"];
            };
        };
        responses: {
            /** @description Person updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listManufacturers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of manufacturers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Manufacturer"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createManufacturer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManufacturerCreate"];
            };
        };
        responses: {
            /** @description Manufacturer created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Manufacturer"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getManufacturer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                manufacturerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Manufacturer retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Manufacturer"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteManufacturer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                manufacturerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Manufacturer deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateManufacturer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                manufacturerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManufacturerUpdate"];
            };
        };
        responses: {
            /** @description Manufacturer updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Manufacturer"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    searchGlobal: {
        parameters: {
            query: {
                /** @description Search query (minimum 2 characters) */
                q: string;
                /** @description Restrict results to the given entity types. Repeat the parameter to request multiple types. */
                types?: components["schemas"]["SearchEntityType"][];
                /** @description Maximum number of results to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemCreate"];
            };
        };
        responses: {
            /** @description Item created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemUpdate"];
            };
        };
        responses: {
            /** @description Item updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listItemTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of item types */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemType"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createItemType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemTypeCreate"];
            };
        };
        responses: {
            /** @description Item type created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemType"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getItemType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item type retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemType"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteItemType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item type deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Item type is currently in use and cannot be deleted */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    updateItemType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemTypeUpdate"];
            };
        };
        responses: {
            /** @description Item type updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemType"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listItemTypeFields: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of item type field definitions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemTypeField"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    replaceItemTypeFields: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemTypeFieldsReplace"];
            };
        };
        responses: {
            /** @description Item type field definitions replaced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemTypeField"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listLabels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of labels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createLabel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelCreate"];
            };
        };
        responses: {
            /** @description Label created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                labelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Label retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                labelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Label deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                labelId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelUpdate"];
            };
        };
        responses: {
            /** @description Label updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listItemLabels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of item labels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    addItemLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemLabelAdd"];
            };
        };
        responses: {
            /** @description Label added to item */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    removeItemLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
                labelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Label removed from item */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listSets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of item sets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemSet"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemSetCreate"];
            };
        };
        responses: {
            /** @description Item set created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemSet"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                setId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item set retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemSet"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                setId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item set deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                setId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemSetUpdate"];
            };
        };
        responses: {
            /** @description Item set updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemSet"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listSetItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                setId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of items in set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetItemWithDetails"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    addSetItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                setId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetItemCreate"];
            };
        };
        responses: {
            /** @description Item added to set */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetItemWithDetails"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    removeSetItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                setId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item removed from set */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateSetItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                setId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetItemUpdate"];
            };
        };
        responses: {
            /** @description Item in set updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetItemWithDetails"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listTrips: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of trips */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTrip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripCreate"];
            };
        };
        responses: {
            /** @description Trip created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getTripRoutePreview: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path: {
                service: "komoot" | "strava" | "wanderer";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Route preview metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripRoutePreview"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getTripById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip details with nested persons, packs, and items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripWithDetails"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripUpdate"];
            };
        };
        responses: {
            /** @description Trip updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    addTripPerson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripPersonCreate"];
            };
        };
        responses: {
            /** @description Person added to trip */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripPersonWithDetails"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    removeTripPerson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                personId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Person removed from trip */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    addTripPersonPack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                personId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripPersonPackCreate"];
            };
        };
        responses: {
            /** @description Pack created and assigned to person in trip */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripPersonPackWithDetails"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    removeTripPersonPack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                personId: string;
                packId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pack removed from person in trip */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    addTripPersonPackItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                personId: string;
                packId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackItemCreate"];
            };
        };
        responses: {
            /** @description Item added to pack */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackItemWithDetails"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    removeTripPersonPackItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                personId: string;
                packId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item removed from pack */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTripPersonPackItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                personId: string;
                packId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackItemUpdate"];
            };
        };
        responses: {
            /** @description Item in pack updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackItemWithDetails"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    addTripPersonItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                personId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripPersonItemCreate"];
            };
        };
        responses: {
            /** @description Item assigned to person in trip */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripPersonItemWithDetails"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    removeTripPersonItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                personId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item removed from person in trip */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTripPersonItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                personId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripPersonItemUpdate"];
            };
        };
        responses: {
            /** @description Item for person in trip updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripPersonItemWithDetails"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listPackingLists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of packing lists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackingList"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createPackingList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackingListCreate"];
            };
        };
        responses: {
            /** @description Packing list created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackingList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getPackingListById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Packing list details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackingList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deletePackingList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Packing list deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updatePackingList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackingListUpdate"];
            };
        };
        responses: {
            /** @description Packing list updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackingList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listPackingListLabels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of packing list labels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    addPackingListLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackingListLabelAdd"];
            };
        };
        responses: {
            /** @description Label added to packing list */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    removePackingListLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listId: string;
                labelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Label removed from packing list */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
