blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/via-justa/overpacked-app/discussions
    about: Please use GitHub Discussions for usage questions and general ideas.
